auto: true
safe: true
server: true
server_port: 4000
baseurl: /
url: http://localhost:4000
exclude: ['init.sh', 'README.md', 'docs/README.md']

markdown: rdiscount
pygments: true
permalink: pretty
paginate: 12
paginate_path: '/blogs/page:num'
